on:
  - "pull_request"
  - "push"

name: "unit"

permissions:
  contents: "read"

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Display Python version"
        run: "python -c 'import sys; print(sys.version)'"

      - name: "Install dependencies"
        run: |
          python -m venv venv
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install --upgrade poetry

      - name: "Install dependencies"
        run: |
          ./venv/bin/poetry env use ./venv/bin/python
          ./venv/bin/poetry install --no-root
          ./venv/bin/poetry env info
          ./venv/bin/poetry config --list

      - name: "Run tests with pytest"
        run: |
          ./venv/bin/poetry env info
          ./venv/bin/python -m coverage run -m unittest discover -s test -p *Test.py
          ./venv/bin/python -m coverage xml

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v4"
        with:
          fail_ci_if_error: true
          files: "test/coverage.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
